name: msub
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  # shared_preferences: ^2.0.20
  get: ^4.6.5
  http: ^1.2.2
  responsive_framework: ^0.2.0

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.0+3
  country_pickers: ^3.0.1
  pin_code_text_field: ^1.8.0
  intl: ^0.19.0
  flutter_calendar_carousel:
    path: ./flutter_calendar_carousel
  # flutter_calendar_carousel: ^2.4.4
#  flutter_calendar_carousel:
#    path: ./flutter_calendar_carousel
  email_validator: ^3.0.0
  image_picker: ^1.1.2
  mime: ^1.0.2
  table_calendar: ^3.1.2
  cached_network_image: ^3.3.1
  flutter_zoom_drawer: ^3.2.0
  dotted_line: ^3.2.3
  flutter_launcher_icons: ^0.14.2
  url_launcher: ^6.3.1
  dropdown_button2: ^2.3.9
  buttons_tabbar: ^1.3.14
  firebase_core: ^3.9.0
  device_info_plus: ^11.2.0
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.5.1
  flutter_secure_storage: ^9.2.4
  go_router: ^14.7.2
  dio: ^5.8.0+1
  fluttertoast: ^8.2.11
  shimmer: ^3.0.0
  flutter_svg: ^2.0.17
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  formz: ^0.8.0
  pinput: ^5.0.1
  clipboard: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets_new/images/
    - assets_new/svgs/
#    - assets/svgs/

  fonts:
      - family: Roboto # Font family name for Roboto
        fonts:
          - asset: assets_new/fonts/Roboto-Regular.ttf
            weight: 400
          - asset: assets_new/fonts/Roboto-Bold.ttf
            weight: 700
          - asset: assets_new/fonts/Roboto-Light.ttf
            weight: 300
          - asset: assets_new/fonts/Roboto-Medium.ttf
            weight: 500

      - family: KoHo # Font family name for KoHo
        fonts:
          - asset: assets_new/fonts/KoHo-Regular.ttf
            weight: 400
          - asset: assets_new/fonts/KoHo-Bold.ttf
            weight: 700
          - asset: assets_new/fonts/KoHo-Light.ttf
            weight: 300
          - asset: assets_new/fonts/KoHo-Medium.ttf
            weight: 500
          - asset: assets_new/fonts/KoHo-SemiBold.ttf
            weight: 600
            
      - family: Poppins # Font family name for KoHo
        fonts:
          - asset: assets_new/fonts/Poppins-ExtraLight.ttf
            weight: 200
          - asset: assets_new/fonts/Poppins-Regular.ttf
            weight: 400
          - asset: assets_new/fonts/Poppins-SemiBold.ttf
            weight: 600
          - asset: assets_new/fonts/Poppins-Medium.ttf
            weight: 500
           