// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHSWGfEsuerR2d8I1SygVWCWosTsvMvGM',
    appId: '1:320168687856:web:41633be8b37b4e26e2aa35',
    messagingSenderId: '320168687856',
    projectId: 'fifth-ventricle-01',
    authDomain: 'fifth-ventricle-01.firebaseapp.com',
    storageBucket: 'fifth-ventricle-01.appspot.com',
    measurementId: 'G-N6GV6RJY0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE0VqJhssshbJsRbUzHJvoCbQSNzIOIIc',
    appId: '1:558349401231:android:b6c82a2df0f20d01e984fa',
    messagingSenderId: '558349401231',
    projectId: 'msub-lms',
    storageBucket: 'msub-lms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsGLqbBnFpMrmNG1Uw4Cu4kMvFA-V01-g',
    appId: '1:320168687856:ios:d81b1fb725b6a265e2aa35',
    messagingSenderId: '320168687856',
    projectId: 'fifth-ventricle-01',
    storageBucket: 'fifth-ventricle-01.appspot.com',
    androidClientId: '320168687856-0o23rku36uvgunld7uo2neslcbun4ed1.apps.googleusercontent.com',
    iosClientId: '320168687856-c77djjhuf69b21gqnj0dspgb7nj9rom9.apps.googleusercontent.com',
    iosBundleId: 'in.fifthventricle.app',
  );
}
